baseurl = "https://www.iyp-uk.com/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "public"
author = "Jerome Krieg"
title = "IYP UK"
pluralizelisttitles = false
googleAnalytics = "UA-107170827-1"

[permalinks]
blog = "blog/:slug/"

[params]
disqusshortname = ""
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "IYP UK's website"
copyright = "Copyright © 2017-2018 IYP UK"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = false
lang = "en"
github = "iyp-uk"
email = ""
linkedin = ""
twitter = ""
social_banner = "img/logo.png"
posts_navigation = true
latestpostcount = 5
